[versions]
commonmark = "0.30.0"
junit-bom = "6.1.2"

[libraries]
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
